# Generated by Django 4.2.7 on 2023-11-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenna',
            field=models.CharField(max_length=100),
        ),
    ]
