# Generated by Django 4.2.7 on 2023-11-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_contrasenna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_maxima',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_minima',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_ida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_vuelta',
            field=models.DateTimeField(),
        ),
    ]
