# Generated by Django 4.2.7 on 2023-11-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cotizacion_fecha_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_maxima',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_minima',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_ida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_vuelta',
            field=models.DateField(),
        ),
    ]
