# Generated by Django 4.2.4 on 2023-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
