# Generated by Django 4.2.4 on 2023-11-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_destino_nombre_alter_tipousuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
