# Generated by Django 4.2.4 on 2023-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_destino_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
